# Generated by Django 4.0.5 on 2022-06-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('', 'Select'), ('smoothie', 'Smoothie'), ('special_smoothie', 'Special Smoothie'), ('special_drink', 'Special Drink'), ('slush', 'Slush'), ('milk_tea', 'Milk Tea'), ('jasmine_tea', 'Jasmine Green Tea'), ('frappe', 'Frappe'), ('milkshake', 'Milkshake'), ('waffle', 'Waffle'), ('milk_snow', 'Milk Snow'), ('acai_pitaya', 'Acai & Pitaya'), ('cafe', 'Cafe'), ('hot_tea', 'Hot Tea'), ('ice_cream', 'Ice Cream'), ('taiyaki', 'Taiyaki')], max_length=255),
        ),
    ]
