# Generated by Django 4.0.5 on 2022-06-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='period',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
