# Generated by Django 4.0.5 on 2022-06-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_story_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='period',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
