# Generated by Django 4.0.5 on 2022-06-29 17:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_story_image_alter_story_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
