# Generated by Django 4.0.5 on 2022-06-30 03:13

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('application_link', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('closed_application_notice', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_title', models.CharField(max_length=255)),
                ('hierarchy', models.CharField(default='1', max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='leader_picture')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinistryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_cover', models.ImageField(upload_to='reading_cover')),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', tinymce.models.HTMLField()),
                ('pdf_link', models.CharField(blank=True, max_length=255)),
                ('pdf_button', models.CharField(blank=True, max_length=255)),
                ('purchase_link', models.CharField(blank=True, max_length=255)),
                ('purchase_button', models.CharField(blank=True, max_length=255)),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=255)),
                ('scripture_passage', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('video_url', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('thumbnail_image', models.ImageField(null=True, upload_to='sermon_thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(null=True, upload_to='upcomingclass_picture')),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingClassDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(null=True, upload_to='upcomingclass_picture')),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(null=True, upload_to='upcomingevent_picture')),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingEventDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(null=True, upload_to='upcomingevent_picture')),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('button_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_extra', models.CharField(blank=True, max_length=255)),
                ('ministry_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries', to='holywave.ministrycategory')),
            ],
        ),
    ]
