# Generated by Django 4.0.5 on 2022-06-30 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holywave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 9, 528365)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='button',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 16, 248951)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ministry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 18, 608113)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ministrycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 19, 953642)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministrycategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 21, 496030)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 22, 808258)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sermon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='upcomingclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 23, 840297)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='upcomingclassdraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 24, 799676)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingclassdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 25, 832491)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='upcomingeventdraft',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 6, 29, 21, 33, 26, 840541)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingeventdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
